# Generated by Django 4.0.6 on 2022-07-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('brand', models.CharField(max_length=200, verbose_name='Марка')),
                ('power', models.IntegerField(verbose_name='Мощность двигателя')),
                ('colour', models.CharField(max_length=200, verbose_name='Цвет')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('delivery_date', models.DateField(verbose_name='Дата поступления в салон')),
                ('sale_date', models.DateField(default=None, verbose_name='Дата продажи')),
            ],
        ),
    ]
