# Generated by Django 4.0.6 on 2022-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinvoicelike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена в рублях'),
        ),
    ]
