# Generated by Django 4.0.6 on 2022-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoinvoicelike', '0002_vehicle_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя дашборда')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата поступления'),
        ),
    ]
